# Note: ConfigMap should be created from the actual test script:
# kubectl create configmap sandbox-stress-test-script \
#   --from-file=test.js=../sandbox-stress-test.js \
#   -n default
#
# kubectl create configmap sandbox-stress-test-data-plane-script \
#   --from-file=test.js=../sandbox-stress-test-data-plane.js \
#   -n default
---
apiVersion: v1
kind: Secret
metadata:
  name: tencent-cloud-credentials
  namespace: default
type: Opaque
stringData:
  TENCENTCLOUD_SECRET_ID: "your_secret_id_here"
  TENCENTCLOUD_SECRET_KEY: "your_secret_key_here"
  E2B_API_KEY: "your_e2b_api_key_here"
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-credentials
  namespace: default
type: Opaque
stringData:
  # InfluxDB connection details
  INFLUXDB_URL: "your_influxdb_url_here"
  INFLUXDB_TOKEN: "your_influxdb_token_here"
  INFLUXDB_ORG: "influxdata"
  INFLUXDB_BUCKET: "default"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-config
  namespace: default
data:
  K6_LOG_LEVEL: "info"
  K6_SUMMARY_TREND_STATS: "avg,min,med,max,p(90),p(95),p(99)"
